# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 14:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=30)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Account',
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='CardInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('issued_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Issuer.Account')),
            ],
            options={
                'db_table': 'CardInstruments',
                'ordering': ['issued_date'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=20)),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'Currency',
                'ordering': ['currency_code'],
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_mcc', models.CharField(max_length=4)),
                ('merchant_name', models.CharField(max_length=100)),
                ('merchant_city', models.CharField(max_length=50)),
                ('merchant_country', models.CharField(max_length=30)),
                ('bank_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Issuer.Account')),
            ],
            options={
                'db_table': 'Merchant',
                'ordering': ['merchant_name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_status', models.CharField(blank=True, max_length=10)),
                ('transaction_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('acquirer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='Issuer.Account')),
                ('billing_currency', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bill_currency', to='Issuer.Currency')),
                ('issuer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='Issuer.Account')),
                ('transaction_currency', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trans_currency', to='Issuer.Currency')),
            ],
            options={
                'db_table': 'Transaction',
                'ordering': ['transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transfer_type', models.CharField(max_length=20)),
                ('transfer_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_details', to='Issuer.Account')),
                ('transaction_id', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Issuer.Transaction')),
            ],
            options={
                'db_table': 'Transfer',
                'ordering': ['transfer_date'],
            },
        ),
    ]
