# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Issuer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='billing_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bill_currency', to='Issuer.Currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trans_currency', to='Issuer.Currency'),
        ),
    ]
