# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Issuer', '0004_auto_20170220_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='settlement_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='settlement_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='settle_currency', to='Issuer.Currency'),
        ),
    ]
